theme: jekyll-theme-minimal
search_enabled: false
title: Lindsay Jacobs
description: University of Wisconsin–Madison <br> <br> <img src="docs/lindsay-jacobs-mutlu.png" width="70%" height="70%">

github:
  is_project_page: false
